name: WakaTime Stats Updater

on:
  schedule:
    # Runs daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with WakaTime Stats
    runs-on: ubuntu-latest
    
    # 🚨 NOTE: This is not needed if using a PAT, but we keep it for safety.
    permissions:
      contents: write 
      actions: read    

    steps:
      - uses: actions/checkout@v4

      # Using the stable anmol098 action.
      - name: Get WakaTime stats and update README
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # 💥 CRITICAL FIX: Use the new PAT instead of the default GITHUB_TOKEN
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          SECTION_NAME: waka
          SHOW_LANGUAGE: "True"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
          SHOW_COMMIT: "False"
